### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by adamrossweiner** [mevCJ/logo-packer#1]
<img width="382" alt="Screen Shot 2021-02-10 at 9 49 50 AM" src="https://user-images.githubusercontent.com/78862741/107525938-55d86700-6b85-11eb-870f-91160be6e2f9.png">
First time user on GitHub, sorry if this isn't the right way of reporting issues.  Updated Adobe CC apps yesterday, downloaded this today and it's not working. Red circle on the icon, nor does any text appear. Please advise. Excited to use, nevertheless!

**Comment by mevCJ** [comment]
Thanks for reporting the issue. May I know the version of your Illustrator?

**Comment by adamrossweiner** [comment]
25.2

—
Adam Ross Weiner

**Comment by mevCJ** [comment]
Hi, I've included a new .zxp package at  [Gumroad](https://gum.co/logo-packer) . Please try it out, thank you!

**Comment by adamrossweiner** [comment]
How do I install it?  I put it in the folder and it still won’t work… it’s probably on my end given I’m novice, but please do advise.

Thanks!

—
Adam Ross Weiner

**Comment by mevCJ** [comment]
Please install it via [ZXPInstaller](https://zxpinstaller.com/). Will add the instructions into the documentation soon! 😄

**Comment by adamrossweiner** [comment]
It still doesn’t work…

—
Adam Ross Weiner

**Comment by mevCJ** [comment]
Please refer to the steps below. Sorry for the errors!

Enabling debug mode:
Win: regedit > HKEY_CURRENT_USER/Software/Adobe/CSXS.9, (CSXS.8 for CC 2018) then add a new entry PlayerDebugMode of type "string" with the value of "1".

macOS: In the terminal, type: defaults write com.adobe.CSXS.10 PlayerDebugMode 1 (The plist is also located at /Users//Library/Preferences/com.adobe.CSXS.10.plist) (CSXS.8 for CC2018)
