### ISSUE TITLE
Noticed some minor things

### ISSUE THREAD

**Issue by schroef** [mevCJ/logo-packer#2]
Bumped into this yesterday and was very pleased that i did. I had been working on and now for while off on something like this. I got couple scripts gathered and customized to do some automated work. Your is already great!

I did notice some small things of issues. First the EPS doesnt do export and also had typos. I havent looked much into that part yet, i dont use the file-format that much anymore. Its ancient! Also Not all format get saved into folders. Ive already added SVG now, im also planning of doing the same to the AI and PDF format. I normally use 3 formats when exporting for display and 2 for print. Perhaps if more options are added users could use their custom export formats. Could be nice, would need pretty heavy coding i guess. 

I also noticed old code and none used scripts. Though i think that CEP dropper is nice, not sure it will work again. It mainly uses copy/paste function. But paste doesnt work anymore in chrome and other browsers. Not sure how long ago he made that, didnt look that long ago. However, we can use a paste command from illustrator. So this does work when using selections. I think that was you original idea right? I also had been looking for something like this, but it was way more complicated what ive found.

You current method does work just as fine as well. Im doing some adjustments to my personal needs for now. I prefer all names also have the clients name in the filles. Im a graphic designer aswell and its quite common to do this. Also i use shortened named, because it also add stuff like rgb/cmyk, hor/ver, mostly those 2 extra things.

**Comment by schroef** [comment]
He ive been doing some work on the addon, i got drag n drop working. I did change the workflow a bit. But now i got some small issues with the file naming. Nothing that difficult. I did change a bit how you were running the script. Its faster now, you reopened the document each time after an export, thats slows down. 

I also added Print and Digital as an option. I need to polish it a bit more and also need to check how i can implement more settings.

![logo-packer-adjustments](https://user-images.githubusercontent.com/6923008/119163266-3de86d00-ba29-11eb-8a8c-256eb144fffd.gif)

**Comment by mevCJ** [comment]
> He ive been doing some work on the addon, i got drag n drop working. I did change the workflow a bit. But now i got some small issues with the file naming. Nothing that difficult. I did change a bit how you were running the script. Its faster now, you reopened the document each time after an export, thats slows down.
> 
> I also added Print and Digital as an option. I need to polish it a bit more and also need to check how i can implement more settings.
> 
> ![logo-packer-adjustments](https://user-images.githubusercontent.com/6923008/119163266-3de86d00-ba29-11eb-8a8c-256eb144fffd.gif)

Sorry for the late response. This looks amazing! Eager to see how you made the drag and drop works.  I'm very new to Adobe plugin development and the project is just something basic that I made for myself to save time. Never thought that someone would be interested in improving it 😆. Glad to have someone who has more experience to work on this! Feel free to play around it, looking forward to the pull request.

**Comment by schroef** [comment]
Yeah man i love it! As i said ive been tinkering with this idea myself. I do logo now and then for work and th export process is tedious en boring, it takes a lot of time doing it over and over again. I had some scripts already for some basic steps but did not find the time yet to do full work on it. I already saw this commercial version. Its called [Logo Package Express]( https://thelogopackage.com/), it was at a nice price of $50 but its raised to $119. Thats is still not much if you see how it works though and how much time it saves you. That version has much more options added since version 2.0. A couple of the ideas he has i also use when exporting logos. 

Im still thinking about adding some more options like adding margins around the logos and perhaps use customizable export settings. That part is a bit more difficult though.

I also had looked at the drag n drop and could get it to work earlier. Then i noticed your script, its a lib right? And found the page which has it. Then i started playing around and got it somewhat working. A perfect method would be how Logo Package Express has it. So you drop in all types of logos and it shows a preview and then it makes all variations. Its the same as the Asset Exporter inside illustrator. Perhaps if i study it a bit more i could get it to work like this.

This week i also added import and export for all the settings. So a user can reuse the settings, its not much users can preset now, but it something to start with. Perhaps as i add more options it can be usefull.

Another idea i had is to let users customize their folder structure. Currently i use the method by the naming of the labels. In this case its as following: Media / File Type. I think its nice if we also add Logo type, that way its ordend a bit better.
Perhaps its nice if users could use an input field with comma separated values, then it will setup the folders accordingly. Could be nice touch.

One thing i need to address is when a user has a custom version of a logo. Quite often i /other make a full color logo with white text or a logo in a single color. Currently the script runs over a preset number of artboards each time. I would need to tinker a bit more with that part so its more dynamic.

Another idea is that the exporter perhaps needs tabs or something. Its already getting a bit long n height. I was thinking of only showing the export settings after a logo gas been generated.

This is how it looks with the added import, export and save settings added. I will do some more work on the icons, some i dont find very clear. The import and export look to thin perhaps
![logopack-v026-2](https://user-images.githubusercontent.com/6923008/120012193-3129c300-bfad-11eb-9d20-9f0855ad1115.png)

Ive also added an automated method for adding logo type descriptions. This is handy if you want to save this sheet with all logo variations.
![added-automated-logo-description](https://user-images.githubusercontent.com/6923008/120013124-5ec33c00-bfae-11eb-8ffb-feeb7f576497.png)

PS ill make a branch today so you can check it out if you want. I did had use the NODE-JS part for adding the JSON loading import/export. I got this from someone elses code. But perhaps i should use a more simplified method. Because of this method he used i needed to add more scripts and do some coding different. Im not really familiar with that. Im not a coder actually, im a designer and do some scripting now and then.
![logo-packer-v026](https://user-images.githubusercontent.com/6923008/120012991-39cec900-bfae-11eb-84be-151f077b7474.gif)

I jsut now noticed that when i use the drag and drop it actually does paste in the SVG code. That didnt work before, not sure why it does now suddenly. That means i can use previews when you drop a logo onto the panel. Thats really nice

Ive also added 2 more features like opening the export folder and also cleaning it. Say you made an error and want to re-export everything. The cleaning function will delete all files quite fast. you can also do it manually of course, i though this is a nice touch, it could be added to export function. Currently when you do AI format and the files already exist, it will show a dialog with a warning. Thats a default dialog from illustrator

**Comment by mevCJ** [comment]
> Yeah man i love it! As i said ive been tinkering with this idea myself. I do logo now and then for work and th export process is tedious en boring, it takes a lot of time doing it over and over again. I had some scripts already for some basic steps but did not find the time yet to do full work on it. I already saw this commercial version. Its called [Logo Package Express](https://thelogopackage.com/), it was at a nice price of $50 but its raised to $119. Thats is still not much if you see how it works though and how much time it saves you. That version has much more options added since version 2.0. A couple of the ideas he has i also use when exporting logos.
> 
> Im still thinking about adding some more options like adding margins around the logos and perhaps use customizable export settings. That part is a bit more difficult though.
> 
> I also had looked at the drag n drop and could get it to work earlier. Then i noticed your script, its a lib right? And found the page which has it. Then i started playing around and got it somewhat working. A perfect method would be how Logo Package Express has it. So you drop in all types of logos and it shows a preview and then it makes all variations. Its the same as the Asset Exporter inside illustrator. Perhaps if i study it a bit more i could get it to work like this.
> 
> This week i also added import and export for all the settings. So a user can reuse the settings, its not much users can preset now, but it something to start with. Perhaps as i add more options it can be usefull.
> 
> Another idea i had is to let users customize their folder structure. Currently i use the method by the naming of the labels. In this case its as following: Media / File Type. I think its nice if we also add Logo type, that way its ordend a bit better.
> Perhaps its nice if users could use an input field with comma separated values, then it will setup the folders accordingly. Could be nice touch.
> 
> One thing i need to address is when a user has a custom version of a logo. Quite often i /other make a full color logo with white text or a logo in a single color. Currently the script runs over a preset number of artboards each time. I would need to tinker a bit more with that part so its more dynamic.
> 
> Another idea is that the exporter perhaps needs tabs or something. Its already getting a bit long n height. I was thinking of only showing the export settings after a logo gas been generated.
> 
> This is how it looks with the added import, export and save settings added. I will do some more work on the icons, some i dont find very clear. The import and export look to thin perhaps
> ![logopack-v026-2](https://user-images.githubusercontent.com/6923008/120012193-3129c300-bfad-11eb-9d20-9f0855ad1115.png)
> 
> Ive also added an automated method for adding logo type descriptions. This is handy if you want to save this sheet with all logo variations.
> ![added-automated-logo-description](https://user-images.githubusercontent.com/6923008/120013124-5ec33c00-bfae-11eb-8ffb-feeb7f576497.png)
> 
> PS ill make a branch today so you can check it out if you want. I did had use the NODE-JS part for adding the JSON loading import/export. I got this from someone elses code. But perhaps i should use a more simplified method. Because of this method he used i needed to add more scripts and do some coding different. Im not really familiar with that. Im not a coder actually, im a designer and do some scripting now and then.
> ![logo-packer-v026](https://user-images.githubusercontent.com/6923008/120012991-39cec900-bfae-11eb-84be-151f077b7474.gif)
> 
> I jsut now noticed that when i use the drag and drop it actually does paste in the SVG code. That didnt work before, not sure why it does now suddenly. That means i can use previews when you drop a logo onto the panel. Thats really nice
> 
> Ive also added 2 more features like opening the export folder and also cleaning it. Say you made an error and want to re-export everything. The cleaning function will delete all files quite fast. you can also do it manually of course, i though this is a nice touch, it could be added to export function. Currently when you do AI format and the files already exist, it will show a dialog with a warning. Thats a default dialog from illustrator

Sounds like a major improvement. Thanks a lot for your contribution! I'll add you into the contributors list if you don't mind :)

**Comment by schroef** [comment]
Sorry for the long wait, i just pushed my edits. Im planning to add some items. Mainly the issue when exporting JPG when part of logo is to small for the scale-up size. Some more items related to folder structure, perhaps custom settings. 

The code is not cleaned, its bloated with unused code. Im no coder so i dont work very clean when im doing testing, i like to keep unused function till im 100% sure i wont use it, then i clean code when im 100%

I also just noticed that i didnt push my latest work, i did this push at work and i seemed to forgot to copy my local work at home to my revision folder. ill do that later. It seems im missing some work ive done.

EDIT
it is the correct version actually, its seems at work where we have 2018cc the panel reacts slower. One function doesnt seem to update panel while its doing the export work. Ill try to figure that out

**Comment by schroef** [comment]
PS the save settings automatically saves all settings inside a settings folder inside the CEP extension folder. The export function does sort of the same, yet you can set a custom location.
Here i need to do some work on the folder, currently it uses a string and is not really connected to export code. Therefor when you import settings it looks like the export folder is set, but you still need to set a folder manually. Still trying figure out better approach for this.

**Comment by mevCJ** [comment]
@schroef Just seen the latest updates, and it's amazing! I made some changes on the input arrangement and removed dnd support temporarily as it is [not supported by the current CEF version](https://www.magpcss.org/ceforum/viewtopic.php?f=6&t=18097). 

The inputs are now grouped into "Generate logo" and "Export logo" separately.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/35603131/140599270-05e6c669-50a7-4ced-bc44-e8205ab33296.png">

The new version will be uploaded to Adobe Exchange for public access. Once again thanks for your contributions!

@all-contributors please add @schroef for code

**Comment by schroef** [comment]
Well I did get drag n drop to work, i need to check it again a. Have not worked with or on for a while actually

**Comment by mevCJ** [comment]
The plugin is now on [Adobe Exchange](https://exchange.adobe.com/creativecloud.details.106003.logo-packer.html) (after a year lol)! I'm closing this thread for now. Once again, @schroef thanks for your contribution 😁

**Comment by schroef** [comment]
I still have to fix the issue where to the logo is to small for jog export. Had parts of code working for this. I need to recheck that code and see if it still works correctly. Basically i runs a check on the logo size, then if it's to small it will resize it so it will export with jpg export settings

**Comment by schroef** [comment]
I still have to fix the issue where to the logo is to small for jog export. Had parts of code working for this. I need to recheck that code and see if it still works correctly. Basically i runs a check on the logo size, then if it's to small it will resize it so it will export with jpg export settings 

Ps perhaps a a link so they can report bugs!
We could add that in the right CL co menu or the CEp panel menu

EDIT
Well i had already put the github there, forgot about that
![Screen Shot 2022-05-18 at 14 19 51](https://user-images.githubusercontent.com/6923008/169116947-f694f060-061f-4b90-9dc0-3d9cae873631.png)
